 language: cpp

 compiler: gcc

 before_install:
  - sudo add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) multiverse"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) restricted"
  - sudo apt-get update -q
  - sudo apt-get install -q git cmake git-core autoconf automake  libtool g++ python-dev swig 
  - sudo apt-get install -q pkg-config libboost1.48-all-dev libfftw3-dev libcppunit-dev libgsl0-dev 
  - sudo apt-get install -q libusb-dev sdcc libsdl1.2-dev python-wxgtk2.8 python-numpy 
  - sudo apt-get install  -q python-cheetah python-lxml doxygen python-qt4 python-qwt5-qt4 libxi-dev 
  - sudo apt-get install -q libqt4-opengl-dev libqwt5-qt4-dev libfontconfig1-dev libxrender-dev

 before_script:
   - git submodule init
   - git submodule update
   - mkdir build
   - cd build
   - cmake ../

 script: make -j 2

 notifications:
   email:
     - manoj.p.gudi@gmail.com
   on_success: always
   on_failure: always
